[2023-05-08 10:24:12,813->resubmit.py->main():146]DEBUG: Path to QC Report is: /usr/local/bin/python3 /Users/chent/Desktop/KOMP_Project/DCCImagesPipeline/src/resubmit.py
[2023-05-08 10:24:12,813->resubmit.py->main():153]INFO: Connecting to db...
[2023-05-08 10:24:13,368->resubmit.py->process():111]ERROR: [Errno 2] No such file or directory: '/usr/local/bin/python3 /Users/chent/Desktop/KOMP_Project/DCCImagesPipeline/src/resubmit.py'
[2023-05-08 10:24:59,078->resubmit.py->main():146]DEBUG: Path to QC Report is: /Volumes/phenotype/DccQcReports/J_QC_2023-04-19/J_failed_media_20230419.csv
[2023-05-08 10:24:59,079->resubmit.py->main():153]INFO: Connecting to db...
[2023-05-08 10:24:59,519->resubmit.py->process():111]ERROR: [Errno 2] No such file or directory: '/Volumes/phenotype/DccQcReports/J_QC_2023-04-19/J_failed_media_20230419.csv'
[2023-05-08 10:25:00,450->resubmit.py->resubmit():136]INFO: Starts downloading . . .
[2023-05-08 10:25:00,450->resubmit.py->resubmit():138]INFO: Done
